In [1]:
from achest import MarketDataClient
from achest import beautify
import pandas as pd
client = MarketDataClient()

In [2]:
data = client.get(
    ["AAPL"],
    "2026-09-01",        # start (Sunday — won't matter)
    "2026-09-10",        # end = day AFTER last trading day you want
    "daily",
    provider="yahoo"
)
data.head(5)

,timestamp,symbol,provider,open,high,low,close,volume
0,2026-09-01T04:00:00.000Z,AAPL,yahoo,316.980011,327.299988,314.730011,325.130005,53167400
1,2026-09-02T04:00:00.000Z,AAPL,yahoo,326.869995,328.399994,323.529999,324.959991,33776400
2,2026-09-03T04:00:00.000Z,AAPL,yahoo,324.869995,330.809998,324.109985,328.209991,37225800
3,2026-09-04T04:00:00.000Z,AAPL,yahoo,328.309998,328.929993,317.859985,319.970001,39606900
4,2026-09-08T04:00:00.000Z,AAPL,yahoo,317.100006,320.700012,314.899994,316.220001,35477100

In [7]:
df = beautify(client.news("AAPL"))        # nested → flattened table
df.head(5)

,related,category,headline,id,image,source,summary,url,datetime,realUrl
0,AAPL,company,"Apple’s New CEO Gets $55 Million, Then Takes t...",141961722,https://s.yimg.com/rz/stage/p/yahoo_finance_en...,Yahoo,Apple's newest CEO walked into the top job wit...,https://finnhub.io/api/news?id=f68d17d4cdd27ab...,1788918883,https://finnhub.io/api/news?id=f68d17d4cdd27ab...
1,AAPL,company,Apple's Foldable iPhone Debuts Today: Will AAP...,141961091,https://s.yimg.com/rz/stage/p/yahoo_finance_en...,Yahoo,Apple unveils its first foldable iPhone and iP...,https://finnhub.io/api/news?id=e982b9b10637ca3...,1788917238,https://finnhub.io/api/news?id=e982b9b10637ca3...
2,AAPL,company,History Says September Is the Worst Month for ...,141961075,https://s.yimg.com/rz/stage/p/yahoo_finance_en...,Yahoo,It's usually not a good idea to bet against th...,https://finnhub.io/api/news?id=f4771f8c6600d42...,1788915001,https://finnhub.io/api/news?id=f4771f8c6600d42...
3,AAPL,company,"Dow Jones Futures: Dow Breaks Support But AMD,...",141954985,https://s.yimg.com/rz/stage/p/yahoo_finance_en...,Yahoo,Stocks fell Tuesday as oil prices and Treasury...,https://finnhub.io/api/news?id=47d7a5442d85da8...,1788903736,https://finnhub.io/api/news?id=47d7a5442d85da8...
4,AAPL,company,Prop Industry Leader The5ers Brings Single Sto...,141954986,https://s.yimg.com/rz/stage/p/yahoo_finance_en...,Yahoo,"The5ers The5ers London, UK, Sept. 08, 2026 (GL...",https://finnhub.io/api/news?id=ad5a14d387fd403...,1788902820,https://finnhub.io/api/news?id=ad5a14d387fd403...

In [10]:
df = client.analyst("PLTR")
df.head(1)

,period,revenueEstimate,revenueHigh,revenueLow,revenueAnalysts,epsEstimate,epsHigh,epsLow,epsAnalysts,ebitEstimate,ebitHigh,ebitLow,ebitAnalysts,quarter,year
0,2030-12-31,70119130000,76428810000,64903418000,8,14.38,16.06218,12.98947,3,46694236254,52156417381,42179067410,8,None,2030

In [12]:
df = client.shipping_ports(search="Los Angeles")         # auto DF already
print(df)

[]

In [15]:
df = client.crypto("fear-greed")
df.head(5)         # auto DF already

                       date  value classification
0  2026-09-09T22:00:00.000Z     69          Greed
1  2026-09-08T22:00:00.000Z     66          Greed
2  2026-09-07T22:00:00.000Z     69          Greed
3  2026-09-06T22:00:00.000Z     71          Greed
4  2026-09-05T22:00:00.000Z     73          Greed