In [2]:
from achest import MarketDataClient
import pandas as pd
client = MarketDataClient("https://achestv2.misango.me")

In [4]:
data = client.get(
    ["AAPL"],
    "2026-09-21",        # start (Sunday — won't matter)
    "2026-09-23",        # end = day AFTER last trading day you want
    "daily",
    provider="yahoo"
)

ReadTimeout: The read operation timed out

In [6]:
data.head(1)

Empty DataFrame
Columns: []
Index: []

In [10]:
df = client.analyst("PLTR")
df.head(1)

,period,revenueEstimate,revenueHigh,revenueLow,revenueAnalysts,epsEstimate,epsHigh,epsLow,epsAnalysts,ebitEstimate,ebitHigh,ebitLow,ebitAnalysts,quarter,year
0,2030-12-31,70119130000,76428810000,64903418000,8,14.38,16.06218,12.98947,3,46694236254,52156417381,42179067410,8,None,2030

In [12]:
df = client.shipping_ports(search="Los Angeles")         # auto DF already
print(df)

[]

In [15]:
df = client.crypto("fear-greed")
df.head(5)         # auto DF already

                       date  value classification
0  2026-09-09T22:00:00.000Z     69          Greed
1  2026-09-08T22:00:00.000Z     66          Greed
2  2026-09-07T22:00:00.000Z     69          Greed
3  2026-09-06T22:00:00.000Z     71          Greed
4  2026-09-05T22:00:00.000Z     73          Greed